### ISSUE TITLE
404 Page Error

### ISSUE THREAD

**Issue by Emsanator** [oscardias/showthatyouhelp#1]
Hello, Thank you for this script!

I've installed it and I want to run, but home page except I'm getting 404 error for other pages.. 
BASE_URL // example,com/showthatyouhelp/  - 404 Errors
BASE_URL // example,com/showthatyouhelp/index.php/  - System run but images do not appear..

I think it is an error in the .htaccess file, Can you help with this?
Thank you

**Comment by oscardias** [comment]
Hello,

If you have enabled the mod_rewrite in apache, then the problem must be in the .htacess file. You need to use the same path in the .htaccess and in the base_url of your application. From your link it seems you installed the script inside a folder callled showthatyouhelp, in this case your .htaccess should be:

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /showthatyouhelp/index.php/$1 [L]

**Comment by Emsanator** [comment]
Hello,

Yes, working now, thank you so much!
